#!/bin/sh
#
# A small browser kiosk based on Linux for public access points
#
# @file browser-kiosk
# @description browser-kiosk wrapper
# @version v1.0
# @author Innovarew <innovarew.solutions (at) gmail (dot) com> (c) Copyright 2017.
# @copyright (C) 2017 Innovarew Solutions. All Rights Reserved.
# @url https://innovarew.appspot.com
#
# Contact us if you are interested in using our products and services.
#

set -euf
export LANG=C

machine=`uname -m`
dirname=`dirname $0`
basename=browser-kiosk

# Follow the symlink
[ -L $0 ] && dirname=`stat $0 | awk '/^  File:/ {system("dirname "$NF);}'`

# find the proper architecture
execfile=$dirname/$machine/$basename.$machine
if [ ! -x $execfile ]
then
    echo "Not found $execfile" && exit
fi

$execfile "$@"
